### ISSUE TITLE
Segmentation fault on Ubuntu 14.10

### ISSUE THREAD

**Issue by evgkul** [CapsAdmin/goluwa#19]
On Ubuntu 14.10 after opening window goluwa crashes

**Comment by evgkul** [comment]
Sorry, can you give me name of linux distribution, in which it works?

**Comment by CapsAdmin** [comment]
i provide my own binaries so it should in theory work on all distributions (using 15.10 myself) but i know the version of ncurses i compile segfaults for some reason. i don't use curses much myself, i use zerobrane instead

you could try `export CURSES=0` before launching to see if that fixes it. but beware of lua errors and thing not working or lagging etc

**Comment by evgkul** [comment]
Thanks, I will try this
