### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by VioletasTheThird** [CapsAdmin/goluwa#29]
*title*

**Comment by CapsAdmin** [comment]
I moved to gitlab

**Comment by Techbot121** [comment]
28e8bf0

**Comment by CapsAdmin** [comment]
I've been wanting to move back to github actually, or at least automatically mirror. 

I struggle with git (all i know is pretty much commit and merge branches) and one issue I have with this repo is that in the past I used to commit binaries. I tried to delete those binaries but now the commit count has doubled.
