### ISSUE TITLE
How to run examples

### ISSUE THREAD

**Issue by sonoro1234** [CapsAdmin/goluwa#30]
![gif](https://user-images.githubusercontent.com/1795930/49440066-fd49fa00-f7c2-11e8-8e4c-3e90d631c560.gif)
I am on windows7 so I installed powershell and then goluwa.cmd, the first time data was downloaded and 3 windows appear, next time I run goluwa.cmd data dont download again but still three windows.
How can I test an example?

**Comment by CapsAdmin** [comment]
This repo is a little bit out of date as I mainly work from gitlab nowadays (but I plan on merging and using 2 upstreams in the future)

https://gitlab.com/CapsAdmin/goluwa

You can run .\goluwa ide from cmd and an editor with a toolbar that lets you start goluwa and a button that lets you run the currently opened script. They also run on save.

In the version on gitlab I'm trying to make it not depend on any editor and use other methods such as file watching and having a better terminal/cmd console.
